language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t marcelomg123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marcelomg123/docker-react npm run test